apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: django-auth-app
  labels:
    app: backend
spec:
  type: ClusterIP  # Internal access only
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: backend

