apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: django-auth-app
  labels:
    app: frontend
spec:
  replicas: 2  # Run 2 frontend pods
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shehanaclg/kubernetes-example-frontend:latest  # Will be built and loaded into Minikube
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

