apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: django-auth-app
spec:
  accessModes:
    - ReadWriteOnce  # Can be mounted by one pod at a time
  resources:
    requests:
      storage: 5Gi  # Request 5GB of storage
  storageClassName: standard  # Minikube uses "standard" storage class

